export const data = [
    {name: "Two Sum", solved: false, type: "Array", link: "https://leetcode.com/problems/two-sum/"},
    {name: "Best Time to Buy and Sell Stock", solved: false, type: "Array", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"},
    {name: "Contains Duplicate", solved: false, type: "Array", link: "https://leetcode.com/problems/contains-duplicate/"},
    {name: "Product of Array Except Self",solved: false,  type: "Array", link: "https://leetcode.com/problems/product-of-array-except-self/"},
    {name: "Maximum Subarray", solved: false, type: "Array", link: "https://leetcode.com/problems/maximum-subarray/"},
    {name: "Maximum Product Subarray", solved: false, type: "Array", link: "https://leetcode.com/problems/maximum-product-subarray/"},
    {name: "Find Minimum in Rotated Sorted Array", solved: false, type: "Array", link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"},
    {name: "Search in Rotated Sorted Array",solved: false, type: "Array",  link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "3 Sum", solved: false, type: "Array",  link: "https://leetcode.com/problems/3sum/"},
    {name: "Container With Most Water", solved: false, type: "Array", link: "https://leetcode.com/problems/container-with-most-water/"},

    {name: "Sum of Two Integers", solved: false, type: "Binary", link: "https://leetcode.com/problems/sum-of-two-integers/"},
    {name: "Number of 1 Bits", solved: false, type: "Binary",link: "https://leetcode.com/problems/number-of-1-bits/"},
    {name: "Missing Number", solved: false, type: "Binary",link: "https://leetcode.com/problems/missing-number/"},
    {name: "Reverse Bits",solved: false,  type: "Binary",link: "https://leetcode.com/problems/reverse-bits/"},

    {name: "Climbing Stairs", solved: false, type: "Dynamic Programming",link: "https://leetcode.com/problems/maximum-subarray/"},
    {name: "Coin Change", solved: false, type: "Dynamic Programming",link: "https://leetcode.com/problems/maximum-product-subarray/"},
    {name: "Longest Increasing Subsequence", solved: false, type: "Dynamic Programming",link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"},
    {name: "Longest Common Subsequence",solved: false, type: "Dynamic Programming", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "Combination Sum", solved: false, type: "Dynamic Programming", link: "https://leetcode.com/problems/3sum/"},
    {name: "House Robber", solved: false,type: "Dynamic Programming", link: "https://leetcode.com/problems/container-with-most-water/"},

    {name: "House Robber II", solved: false, type: "Dynamic Programming",link: "https://leetcode.com/problems/two-sum/"},
    {name: "Decode Ways", solved: false, type: "Dynamic Programming",link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"},
    {name: "Unique Paths", solved: false, ltype: "Dynamic Programming",ink: "https://leetcode.com/problems/contains-duplicate/"},
    {name: "Jump Game",solved: false, type: "Dynamic Programming", link: "https://leetcode.com/problems/product-of-array-except-self/"},

    {name: "Clone Graph", solved: false, type: "Graph", link: "https://leetcode.com/problems/maximum-subarray/"},
    {name: "Course Schedule", solved: false, type: "Graph",link: "https://leetcode.com/problems/maximum-product-subarray/"},
    {name: "Pacific Atlantic Water Flow", solved: false,type: "Graph", link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"},
    {name: "Number of Islands",solved: false, type: "Graph", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "Alien Dictionary", solved: false, type: "Graph", link: "https://leetcode.com/problems/3sum/"},
    {name: "Graph Valid Tree", solved: false, type: "Graph",link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Number of Connected Components in an Undirected Graph", solved: false, type: "Graph",link: "https://leetcode.com/problems/two-sum/"},
    
    {name: "Insert Interval", solved: false, type: "Interval",link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"},
    {name: "Merge Intervals", solved: false,type: "Interval", link: "https://leetcode.com/problems/contains-duplicate/"},
    {name: "Non-overlapping Intervals",solved: false, type: "Interval",link: "https://leetcode.com/problems/product-of-array-except-self/"},
    {name: "Climbing Stairs", solved: false,type: "Interval", link: "https://leetcode.com/problems/maximum-subarray/"},
    {name: "Meeting Rooms", solved: false, type: "Interval",link: "https://leetcode.com/problems/maximum-product-subarray/"},
    {name: "Meeting Rooms II", solved: false, type: "Interval",link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"},

    {name: "Reverse a Linked List",solved: false,  type: "linked List",link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "Detect Cycle in a Linked List", solved: false,  type:  "Linked List",link: "https://leetcode.com/problems/3sum/"},
    {name: "Merge Two Sorted Lists", solved: false, type:  "Linked List",link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Merge K Sorted Lists",solved: false, type:  "Linked List",link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "Remove Nth Node From End Of List", solved: false, type:  "Linked List", link: "https://leetcode.com/problems/3sum/"},
    {name: "Reorder List", solved: false, type:  "Linked List",link: "https://leetcode.com/problems/container-with-most-water/"},

    {name: "Set Matrix Zeroes", solved: false,  type: "Matrix", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"},
    {name: "Spiral Matrix", solved: false,type: "Matrix", link: "https://leetcode.com/problems/contains-duplicate/"},
    {name: "Rotate Image",solved: false, type: "Matrix", link: "https://leetcode.com/problems/product-of-array-except-self/"},
    {name: "Word Search", solved: false, type: "Matrix",link: "https://leetcode.com/problems/maximum-subarray/"},

    {name: "Longest Substring Without Repeating Characters", solved: false, type:"String", link: "https://leetcode.com/problems/maximum-product-subarray/"},
    {name: "Longest Repeating Character Replacement", solved: false,type:"String", link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"},
    {name: "Minimum Window Substring",solved: false, type:"String", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "Valid Anagram", solved: false, type:"String", link: "https://leetcode.com/problems/3sum/"},
    {name: "Group Anagrams", solved: false, type:"String",link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Valid Parentheses",solved: false, type:"String", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "Valid Palindrome", solved: false,  type:"String",link: "https://leetcode.com/problems/3sum/"},
    {name: "Longest Palindromic Substring", solved: false, type:"String",link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Palindromic Substrings", solved: false,type:"String", link: "https://leetcode.com/problems/maximum-product-subarray/"},
    {name: "Longest Repeating Character Replacement", solved: false, type:"String",link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"},
    {name: "Encode and Decode Strings",solved: false, type:"String", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    
    {name: "Maximum Depth of Binary Tree", solved: false, type:"Tree", link: "https://leetcode.com/problems/3sum/"},
    {name: "Same Tree", solved: false,type:"Tree",  link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Invert/Flip Binary Tree",solved: false, type:"Tree",  link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "Binary Tree Maximum Path Sum", solved: false,  type:"Tree", link: "https://leetcode.com/problems/3sum/"},
    {name: "Binary Tree Level Order Traversal", solved: false,type:"Tree",  link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Serialize and Deserialize Binary Tree", solved: false, type:"Tree", link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Subtree of Another Tree",solved: false, type:"Tree",  link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "Construct Binary Tree from Preorder and Inorder Traversal", solved: false, type:"Tree",  link: "https://leetcode.com/problems/3sum/"},
    {name: "Validate Binary Search Tree", solved: false,type:"Tree",  link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Kth Smallest Element in a BST", solved: false, type:"Tree", link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Lowest Common Ancestor of BST",solved: false, type:"Tree",  link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "Implement Trie (Prefix Tree)", solved: false, type:"Tree",  link: "https://leetcode.com/problems/3sum/"},
    {name: "Add and Search Word", solved: false,type:"Tree",  link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Word Search II", solved: false,type:"Tree",  link: "https://leetcode.com/problems/container-with-most-water/"},

    {name: "Merge K Sorted Lists", solved: false,type:"Heap",  link: "https://leetcode.com/problems/container-with-most-water/"},
    {name: "Top K Frequent Elements",solved: false,  type:"Heap", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
    {name: "Find Median from Data Stream", solved: false, type:"Heap",  link: "https://leetcode.com/problems/3sum/"},

]

